RecipeBox/Models/Ingredient.cs
using System.Collections.Generic;

namespace RecipeBox.Models
{
  public class Ingredient
    {
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public List<RecipeIngredient> JoinEntitiesIngredients { get;}
    }
}

RecipeBox/Controllers/IngredientsController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecipeBox.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly RecipeBoxContext _db;

        public IngredientsController(RecipeBoxContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Ingredients.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Ingredient ingredient)
        {
            _db.Ingredients.Add(ingredient);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            Ingredient thisIngredient = _db.Ingredients
                .Include(ingredient => ingredient.JoinEntitiesIngredients)
                .ThenInclude(join => join.Recipe)
                .FirstOrDefault(ingredient => ingredient.IngredientId == id);
            return View(thisIngredient);
        }
        public ActionResult AddRecipe(int id)
        {
            Ingredient thisIngredient = _db.Ingredients.FirstOrDefault(ingredients => ingredients.IngredientId == id);
            ViewBag.RecipeId = new SelectList(_db.Recipes, "RecipeId", "Description");
            return View(thisIngredient);
        }

        [HttpPost]
        public ActionResult AddRecipe(Ingredient ingredient, int recipeId)
        {
#nullable enable
            RecipeIngredient? joinEntity = _db.RecipeIngredients.FirstOrDefault(join => (join.RecipeId == recipeId && join.IngredientId == ingredient.IngredientId));
#nullable disable
            if (joinEntity == null && recipeId != 0)
            {
                _db.RecipeIngredients.Add(new RecipeIngredient() { RecipeId = recipeId, IngredientId = ingredient.IngredientId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = ingredient.IngredientId });
        }





    }
}

RecipeBox/Views/Ingredients/AddRecipe.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Ingredient

<h2>Add an recipe</h2>

<h4>Add a recipe for this ingredient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.IngredientId)

    @Html.Label("Select recipe")
    @Html.DropDownList("RecipeId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

RecipeBox/Views/Ingredients/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Ingredient

<h4>Add a new ingredient</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    <input type="submit" value="Add a new ingredient" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all the ingredients", "Index")</p>

RecipeBox/Views/Ingredients/Details.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models
@model RecipeBox.Models.Ingredient

<h2>Ingredient Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntitiesIngredients.Count == 0)
{
  <p>This ingredient does not belong to any recipes</p>
}
else
{
  <h4>Recipes this ingredient belongs to:</h4>
  <ul>
  @foreach(RecipeIngredient join in Model.JoinEntitiesIngredients)
  {
    <li>@join.Recipe.Description</li>
    @using (Html.BeginForm("DeleteJoin", "Ingredients"))
    {
      @Html.Hidden("joinId", @join.RecipeIngredientId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add a Recipe", "AddRecipe", new { id = Model.IngredientId})</p>
<p>@Html.ActionLink("Edit Ingredient", "Edit", new { id = Model.IngredientId})</p>
<p>@Html.ActionLink("Delete Ingredient", "Delete", new { id = Model.IngredientId})</p>

RecipeBox/Views/Ingredients/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;

<h1>Ingredients</h1>

@if (@Model.Count == 0)
{
  <h3>No Ingredients have been added yet dummy!</h3>
} 

@foreach (Ingredient Ingredient in Model)
{
  <li>@Html.ActionLink($"{Ingredient.Name}", "Details", new { id = Ingredient.IngredientId })</li>
}

<p>@Html.ActionLink("Add a new Ingredient", "Create")</p>

<p>@Html.ActionLink("Go Back Home", "Index", "Home")</p>